Feature/cli
openscilab/reserver pull request #32
Opened 2024-05-20 22:34 UTC by AHReccese

#### Reference Issues/PRs
#13 
#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-05-25 21:50 UTC, sepandhaghighi requested changes
@AHReccese Thanks for your efforts 💯 
Please take a look at my comments 🥇

2024-05-25 21:50 UTC, sepandhaghighi commented on reserver/reserver_param.py
> +A Python that offers the ability to quickly reserve a PyPI package name.
Wrong overview.

`Reserver is an open source Python package that offers the ability to quickly reserve a PyPI package name. Got a notion? Before it's taken, immediately reserve the product name!`

2024-05-25 21:50 UTC, sepandhaghighi commented on reserver/__main__.py
> +    parser.add_argument('--test', action='store_true', help='Flag identifying test account or not')
My suggestion:

`help='test PyPI (test.pypi.org)`

2024-05-25 21:51 UTC, sepandhaghighi commented on reserver/reserver_param.py
> +A Python that offers the ability to quickly reserve a PyPI package name.
Or

`A Python package that offers the ability to quickly reserve a PyPI package name. Got a notion? Before it's taken, immediately reserve the product name!`

2024-06-07 15:02 UTC, AHReccese commented
@sepandhaghighi 
A kind reminder for the review!
Thanks!

2024-06-10 08:03 UTC, sepandhaghighi requested changes
@AHReccese Thanks for your efforts 💯 

Please take a look at my comments 🔥 

Also:

1. Don't forget to add `entry_points` to `setup.py`

```
entry_points={
            'console_scripts': [
                'reserver = reserver.__main__:main',
            ]
    }
```
2. Add a smoke test (first test) for CLI to workflow. Something like this:

```console
reserver --version
```

2024-06-10 08:03 UTC, sepandhaghighi commented on reserver/__main__.py
> +        required=True
When an argument is required, `--version` and `-v` won't function correctly.

```console
python -m reserver --version
```

```
usage: __main__.py [-h] --name NAME [NAME ...] --token TOKEN [--test] [--version] [-v]
__main__.py: error: the following arguments are required: --name, --token
```

2024-06-10 08:03 UTC, sepandhaghighi commented on reserver/reserver_func.py
> +            raise ReserverBaseError("Given parameter doesn't exist among the supported user allowed parameters.")
I recommend relocating this message to `reserver_params.py`.

2024-06-10 08:03 UTC, sepandhaghighi commented on reserver/reserver_func.py
> +            raise ReserverBaseError("Invalid value for " + parameter + " that should be a valid " + regex)
I recommend relocating this message to `reserver_params.py` and use `format` instead of `+`

2024-06-10 08:03 UTC, sepandhaghighi commented on reserver/__main__.py
> +    names = args.name
I suggest using an `else` statement here to prevent the `--version`(`-v`) and main function from running simultaneously.

```console
python -m reserver --version --name sample_name1 --token=PYPI_TOKEN
```

2024-06-11 13:11 UTC, AHReccese commented on reserver/__main__.py
> +    names = args.name
Which one do you suggest to get done in this command? version check or package reserving?
@sepandhaghighi

2024-06-11 13:16 UTC, AHReccese commented on reserver/__main__.py
> +        required=True
Fixed.

2024-06-11 13:16 UTC, AHReccese commented on reserver/reserver_func.py
> +            raise ReserverBaseError("Given parameter doesn't exist among the supported user allowed parameters.")
Done.

2024-06-11 13:16 UTC, AHReccese commented on reserver/reserver_func.py
> +            raise ReserverBaseError("Invalid value for " + parameter + " that should be a valid " + regex)
Done.

2024-06-11 17:06 UTC, AHReccese commented on reserver/__main__.py
> +    names = args.name
Sepand -> --version
Sadra -> --version
Amir -> --version

so -> --version

2024-06-11 18:54 UTC, AHReccese commented on reserver/__main__.py
> +    names = args.name
Applied.

2024-06-12 15:22 UTC, sepandhaghighi approved these changes
LGTM 🚀

2024-06-12 15:23 UTC, merged